# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

FROM server

RUN npm config set unsafe-perm true

# npm install the dashboard server app
RUN cd /home/node && npm install -g --quiet ./app
WORKDIR /home/node

ENTRYPOINT ["jupyter-dashboards-server"]
